# azure-pipelines.yml

#This is the self-hosted pipeline
trigger:
  - main

pool:
  name: Default

steps:
  - script: |
      echo "Agent OS: $(Agent.OS)"
      echo "Agent name: $(Agent.MachineName)"
    displayName: 'Show environment'
  - script: |
      echo "Using Python 3.12"
      python3.12 --version
    displayName: 'Check Python version'

  - script: |
      echo "Installing dependencies..."
      pip3.12 install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo "Building the project..."
      pytest test_hello_world.py -v
      echo "Build completed successfully."
    displayName: 'Run tests'